name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install uv
        run: pip install uv

      - name: Install dependencies
        run: uv sync --dev

      - name: Check formatting with Ruff
        run: uv run ruff format --check .

      - name: Run type checker
        run: uv run ty check src tests

      - name: Run unit tests
        run: uv run pytest tests/test_writer.py

      - name: Run integration tests
        # This step only runs if the required secrets are available.
        if: ${{ env.LAKEBASE_USER != '' && env.LAKEBASE_PASSWORD != '' && env.LAKEBASE_NAME != '' }}
        env:
          LAKEBASE_USER: ${{ secrets.LAKEBASE_USER }}
          LAKEBASE_PASSWORD: ${{ secrets.LAKEBASE_PASSWORD }}
          LAKEBASE_NAME: ${{ secrets.LAKEBASE_NAME }}
        run: uv run pytest tests/test_integration.py 